using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudentsAdmissionApplication
{
    public class DepartmentDetails
    {
        //department id autogenerated
        private static int s_departmentID=100;
        public string DepartmentID{ get; set; }

        public string Departmentname { get; set; }

        public int NumberOfSeats {get;set;}
        //parameter constructor foe department details class
        public DepartmentDetails(string departmentName,int numberOfSeats)
        {
            s_departmentID++;
            DepartmentID="DID"+s_departmentID;
            Departmentname=departmentName;
            NumberOfSeats=numberOfSeats;
        }

    }
}